# Configuración de la base de datos PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mycoachfit
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  # Configuración de Hibernate (opcional, si estás usando JPA)
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Configuración de la zona horaria (opcional, ajusta según tu preferencia)
# Puedes usar esta línea o la siguiente, no ambas
#   datasource:
#     jdbc-url: jdbc:postgresql://localhost:5432/mycoachfit?serverTimezone=UTC

# Puerto del servidor de la aplicación (ajusta según sea necesario)
server:
  port: 8080